// Generated by CoffeeScript 1.7.1
(function() {
  var Cloth, Runner, UkrainianFlag, Vector3D,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Vector3D = (function() {
    function Vector3D(x, y, z) {
      this.coords = [x, y, z];
    }

    Vector3D.prototype.x = function() {
      return this.coords[0];
    };

    Vector3D.prototype.y = function() {
      return this.coords[1];
    };

    Vector3D.prototype.z = function() {
      return this.coords[2];
    };

    return Vector3D;

  })();

  Cloth = (function() {
    function Cloth(width, height, block_size) {
      var h, w;
      this.width = width;
      this.height = height;
      this.block_size = block_size;
      this.state = (function() {
        var _i, _ref, _results;
        _results = [];
        for (h = _i = 0, _ref = this.height; 0 <= _ref ? _i <= _ref : _i >= _ref; h = 0 <= _ref ? ++_i : --_i) {
          _results.push((function() {
            var _j, _ref1, _results1;
            _results1 = [];
            for (w = _j = 0, _ref1 = this.width; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; w = 0 <= _ref1 ? ++_j : --_j) {
              _results1.push(new Vector3D(w * this.block_size, h * this.block_size, 0));
            }
            return _results1;
          }).call(this));
        }
        return _results;
      }).call(this);
    }

    return Cloth;

  })();

  UkrainianFlag = (function(_super) {
    __extends(UkrainianFlag, _super);

    function UkrainianFlag() {
      UkrainianFlag.__super__.constructor.call(this, 30, 20, 30);
      this.initGeometry();
    }

    UkrainianFlag.prototype.initGeometry = function() {
      var blue, face, i, j, point, row, _i, _j, _k, _l, _len, _len1, _ref, _ref1, _ref2;
      this.geometry = new THREE.Geometry();
      blue = new THREE.Color(0x00ffff);
      _ref = this.state;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        row = _ref[_i];
        for (_j = 0, _len1 = row.length; _j < _len1; _j++) {
          point = row[_j];
          this.geometry.vertices.push((function(func, args, ctor) {
            ctor.prototype = func.prototype;
            var child = new ctor, result = func.apply(child, args);
            return Object(result) === result ? result : child;
          })(THREE.Vector3, point.coords, function(){}));
        }
      }
      for (i = _k = 0, _ref1 = this.height; 0 <= _ref1 ? _k < _ref1 : _k > _ref1; i = 0 <= _ref1 ? ++_k : --_k) {
        for (j = _l = 0, _ref2 = this.width; 0 <= _ref2 ? _l < _ref2 : _l > _ref2; j = 0 <= _ref2 ? ++_l : --_l) {
          face = new THREE.Face3(i * (this.width + 1) + j, i * (this.width + 1) + j + 1, (i + 1) * (this.width + 1) + j + 1, null, null, i >= this.height / 2 ? 0 : 1);
          this.geometry.faces.push(face);
          face = new THREE.Face3(i * (this.width + 1) + j, (i + 1) * (this.width + 1) + j + 1, (i + 1) * (this.width + 1) + j, null, null, i >= this.height / 2 ? 0 : 1);
          this.geometry.faces.push(face);
        }
      }
    };

    UkrainianFlag.prototype.mesh = function() {
      var material, material_blue, material_yellow;
      material_blue = new THREE.MeshBasicMaterial({
        color: 0x0057b8,
        wireframe: true
      });
      material_yellow = new THREE.MeshBasicMaterial({
        color: 0xffd700,
        wireframe: true
      });
      material = new THREE.MeshFaceMaterial([material_blue, material_yellow]);
      return new THREE.Mesh(this.geometry, material);
    };

    return UkrainianFlag;

  })(Cloth);

  Runner = (function() {
    function Runner(mesh) {
      this.animate = __bind(this.animate, this);
      this.camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 1, 10000);
      this.camera.position.z = 1000;
      this.scene = new THREE.Scene();
      this.scene.add(mesh);
      this.renderer = new THREE.CanvasRenderer();
      this.renderer.setSize(window.innerWidth, window.innerHeight);
      document.body.appendChild(this.renderer.domElement);
      return;
    }

    Runner.prototype.animate = function() {
      requestAnimationFrame(this.animate);
      this.renderer.render(this.scene, this.camera);
    };

    Runner.prototype.run = function() {
      return this.animate();
    };

    return Runner;

  })();

  $(function() {
    var flag;
    flag = new UkrainianFlag();
    return new Runner(flag.mesh()).run();
  });

}).call(this);
